ALTER TABLE employees
ADD CONSTRAINT personal_number_unique UNIQUE (personal_number);

ALTER TABLE employees
ADD CONSTRAINT email_unique UNIQUE (email);

ALTER TABLE payments
RENAME COLUMN TOTAL_RETENTIOS TO TOTAL_RETENTIONS;

ALTER TABLE payments MODIFY (PAY_DATE NULL);
ALTER TABLE payments MODIFY (TOTAL_BENEFITS NULL);
ALTER TABLE payments MODIFY (TOTAL_RETENTIONS NULL);
ALTER TABLE payments MODIFY (TOTAL_LICENSES NULL);
ALTER TABLE payments MODIFY (TOTAL_TAXES NULL);
ALTER TABLE payments MODIFY (TOTAL NULL);
ALTER TABLE payments MODIFY (PERIOD NULL);

ALTER TABLE paymentconcepts MODIFY (amount NULL);

ALTER TABLE payments
ADD finished number NULL;

ALTER TABLE type_concept
RENAME COLUMN type TO name_type;

ALTER TABLE employees
MODIFY (abb_currency VARCHAR2(5));
