
--Borrar tablespace
DROP TABLESPACE TECH_DATA;
DROP TABLESPACE TECH_DATA_IDX;


CREATE TABLESPACE TECH_DATA LOGGING DATAFILE 
'C:\oracleXE\oradata\XE\TechNomina\TECH_DATA.dbf' SIZE 10M
AUTOEXTEND ON MAXSIZE 100M;

CREATE TABLESPACE TECH_DATA_IDX LOGGING DATAFILE 
'C:\oracleXE\oradata\XE\TechNomina\TECH_DATA_IDX.dbf' SIZE 10M 
AUTOEXTEND ON MAXSIZE 100M;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER NOMINA
PROFILE DEFAULT IDENTIFIED BY 
123 DEFAULT TABLESPACE 
TECH_DATA TEMPORARY TABLESPACE 
TEMP ACCOUNT UNLOCK;


--Para usarlo no olvidar darle PERMISOS DE CONEXION
GRANT CONNECT TO NOMINA;
GRANT RESOURCE TO NOMINA;
ALTER USER NOMINA QUOTA UNLIMITED ON TECH_DATA;

--CREATE INDEX IX_CLIENTE_NOMBRE ON CLIENTE(NOMBRE) 
--TABLESPACE TEST_DATA_IDX;

select * from dba_users;
 
